# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane
platform :ios do
  before_all do |lane, options|
    app_store_connect_api_key()  #authenticating with App Store Connect 
  end

  desc "Push a new beta build to TestFlight"
  lane :beta do
    sh "cp #{ENV["BRAND_ENV_PACKAGE_NAME"]} ../../.env"
    sh "cp #{ENV["BRAND_GOOGLE_SERVICE_INFO"]} ../app/GoogleService-Info.plist"
    sh "cd .. && yarn prepare-release"

    produce(
      username: ENV["APPLE_USERNAME"],
      app_identifier: ENV["BRAND_ID"],
      app_name: ENV["BRAND_APPNAME"],
      language: "English",
      team_name: ENV["COMPANY_NAME"],
      enable_services: {
        push_notification: "on", 
      }
    )

    match(
      git_url: "git@github.com:username/repository.git",
      type: "appstore",
      readonly: false
    )

    sigh(
      username: ENV["APPLE_USERNAME"],
      app_identifier: ENV["BRAND_ID"],
      output_path: "provisioning_profiles",
      team_name: ENV["COMPANY_NAME"]
    )

    update_project_provisioning(
      xcodeproj: "app.xcodeproj",
      profile: ENV["SIGH_PROFILE_PATH"],
      target_filter: "app",
      build_configuration: "Release",
      code_signing_identity: "Apple Distribution: #{ENV["COMPANY_NAME"]}. (#{ENV["TEAM_ID"]})"
    )

    gym(
      workspace: "app.xcworkspace",
      scheme: "app",
      silent: true, 
      xcargs: "-allowProvisioningUpdates", 
    )
    testflight
  end

  desc "Push all apps beta build to TestFlight"
  lane :all_apps_beta do
    sh "bundle exec fastlane ios beta --env app1"
    #sh "bundle exec fastlane ios beta --env app2"
  end

  desc "Push a new app build to release"
  lane :release do
    sh "cp #{ENV["BRAND_ENV_PACKAGE_NAME"]} ../../.env"
    sh "cp #{ENV["BRAND_GOOGLE_SERVICE_INFO"]} ../app/GoogleService-Info.plist"
    sh "cd .. && yarn prepare-release"

    produce(
      username: ENV["APPLE_USERNAME"],
      app_identifier: ENV["BRAND_ID"],
      app_name: ENV["BRAND_APPNAME"],
      language: "English",
      team_name: ENV["COMPANY_NAME"],
      enable_services: {
        push_notification: "on", 
      }
    )

    match(
      git_url: "git@github.com:username/repository.git",
      type: "appstore",
      readonly: false
    )

    sigh(
      username: ENV["APPLE_USERNAME"],
      app_identifier: ENV["BRAND_ID"],
      output_path: "provisioning_profiles",
      team_name: ENV["COMPANY_NAME"]
    )

    update_project_provisioning(
      xcodeproj: "app.xcodeproj",
      profile: ENV["SIGH_PROFILE_PATH"],
      target_filter: "app",
      build_configuration: "Release",
      code_signing_identity: "Apple Distribution: #{ENV["COMPANY_NAME"]}. (#{ENV["TEAM_ID"]})"
    )

    get_push_certificate

    gym(
      workspace: "app.xcworkspace",
      scheme: "app",
      silent: true, 
      xcargs: "-allowProvisioningUpdates", 
    )
    upload_to_app_store
  end
  
  desc "Push all apps release build to AppStore"
  lane :all_apps_release do
    sh "bundle exec fastlane ios release --env app1"
    sh "bundle exec fastlane ios release --env app2"
  end
end  
